version: '3'

tasks:
  default:
    cmds:
      - air -c .air.toml

  setup:
    cmds:
      - go mod tidy
      - go install -v github.com/go-critic/go-critic/cmd/gocritic@latest
      - go install

  lint:
    cmds:
      - gocritic check -enableAll ./...

  test:
    cmds:
      - go test ./...

  test-cov:
    cmds:
      - go test -cover ./...

  build:
    cmds:
      - go build

  gen:
    cmds:
      - go generate

  docker-build:
    cmds:
      - docker build . -t {{cookiecutter.org_name}}-{{cookiecutter.package_name}}
