on: [push, pull_request]

name: Pull Requests

jobs:
  build-template:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
          python-version: ['3.8', '3.9', '3.10']
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Display Python version
          run: pip install cookiecutter

        - name: Create template
          run: cookiecutter --no-input .

        - name: Archive result
          uses: actions/upload-artifact@v2
          with:
            name: result
            path: api

  build-and-test-result:
    name: Build and test cookiecutter result

    needs: build-template

    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: result

      - name: Tidy
        run: go mod tidy

      - name: Install
        run: go install

      - name: Install Task
        run: go get -u github.com/go-task/task/v3/cmd/task

      - name: Build
        run: task build

      - name: Test
        run: task test

  build-docker:
    name: Build docker from cookiecutter result

    needs: build-template

    strategy:
      matrix:
        go-version: [1.19.x]

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: result

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Task
        run: go get -u github.com/go-task/task/v3/cmd/task

      - name: Docker Build
        run: task docker-build
